### ISSUE TITLE
Image Enhancements

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/indigo-streamdeck#2]
I have modified the Stream Deck plugin images and manifest and attach files for your consideration.

The images have been modified to more closely follow the [style guide](https://developer.elgato.com/documentation/stream-deck/sdk/style-guide/). The images main change is to move the Indigo House up on the Key image so that any text on the bottom of the key isn't obscured. The Action Image now follows the guide "Action Image should be single color #d8d8d8 rgb(216,216,216)". The manifest.json file is modified to add in a Category label of "Indigo" that replaces the previous Custom category. Also changed the pointer for the Actions Icon.

Example Output:
![revised images](https://user-images.githubusercontent.com/11138074/117539514-eb5b8980-b002-11eb-8be1-a1a40a19f00d.png)

indigoActionIcon:
![indigoActionIcon](https://user-images.githubusercontent.com/11138074/117539519-f7474b80-b002-11eb-9c3d-a268feccccaa.png)

indigoActionIcon@2x:
![indigoActionIcon@2x](https://user-images.githubusercontent.com/11138074/117539520-f7474b80-b002-11eb-8887-04af1e0499d0.png)

indigoCategoryIcon:
![indigoCategoryIcon](https://user-images.githubusercontent.com/11138074/117539521-f7dfe200-b002-11eb-9ca9-36c6b77cff28.png)

indigoCategoryIcon@2x
![indigoCategoryIcon@2x](https://user-images.githubusercontent.com/11138074/117539522-f7dfe200-b002-11eb-904e-d441452cbab6.png)

indigoIcon:
![indigoIcon](https://user-images.githubusercontent.com/11138074/117539523-f7dfe200-b002-11eb-8ea6-2cd847a93763.png)

indigoIcon@2x
![indigoIcon@2x](https://user-images.githubusercontent.com/11138074/117539524-f8787880-b002-11eb-920f-d4a410a1a0a7.png)

Revised manifest.json file:
```json
{
  "Actions": [
    {
      "Icon": "images/indigoActionIcon", 
      "Name": "Indigo Action", 
      "States": [
        {
          "Image": "images/indigoIcon"
        }
      ], 
      "Tooltip": "Send action request to Indigo", 
      "UUID": "com.flyingdiver.indigo.action"
    }
  ], 
  "Author": "FlyingDiver", 
  "CodePath": "plugin/app.html",
  "Category": "Indigo", 
  "CategoryIcon": "images/indigoCategoryIcon", 
  "Description": "Connects the StreamDeck to the Indigo home automation system", 
  "Icon": "images/indigoIcon", 
  "Name": "Indigo Bridge", 
  "PropertyInspectorPath": "pi/pi.html", 
  "SDKVersion": 2,
  "URL": "https://github.com/FlyingDiver/indigo-streamdeck", 
  "Version": "0.0.2",
  "OS": [
    {
        "Platform": "mac", 
        "MinimumVersion" : "10.11"
    },
    {
        "Platform": "windows", 
        "MinimumVersion" : "10"
    }
  ],
  "Software": 
    {
        "MinimumVersion" : "4.1"
  }
}

```

**Comment by FlyingDiver** [comment]
Merged to master
