### ISSUE TITLE
Version 0.0.3 Not saving fields?

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/indigo-streamdeck#3]
Installed V0.0.3 of the Indigo plugin, installed the associated stream deck plugin, closed stream deck and restarted stream deck.

In the Stream Deck Indigo Action, I can enter the Indigo Server IP address, Indigo Action and Action Info (device Id). If I then click on another Key and then come back to the Indigo Action, The Indigo Server IP address is greyed out to a value of 127.0.0.1:9001 i.e. the value I put in has disappeared. So I enter it again and then If I click on another key and then back onto the Indigo Action, The Indigo IP address is still there but the Indigo Action and Indigo Info fields are blank. Hope that makes sense?

**Comment by FlyingDiver** [comment]
As much as any of the Javascript crap makes sense.

**Comment by FlyingDiver** [comment]
Clearly my attempt to save the Indigo IP address along with the action info failed.

**Comment by FlyingDiver** [comment]
I'll look at it again.

**Comment by FlyingDiver** [comment]
This is all part of issue #1 .
